import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve('src');
const css = readFileSync(join('dist/assets', readdirSync('dist/assets').find((f) => f.endsWith('.css'))), 'utf8');

const files = [];
(function walk(dir) {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) walk(p);
    else if (/\.(tsx|ts)$/.test(p)) files.push(p);
  }
})(ROOT);

const escape = (s) => s.replace(/([\\/:[\]().%#])/g, '\\$1');

const VARIANTS = '(?:[a-z0-9-]+:)*';
const PREFIXES = [
  'text', 'bg', 'border', 'ring', 'divide', 'from', 'via', 'to', 'shadow', 'outline',
  'fill', 'stroke', 'placeholder', 'decoration', 'accent', 'caret', 'space', 'gap',
  'px', 'py', 'pt', 'pb', 'pl', 'pr', 'mx', 'my', 'mt', 'mb', 'ml', 'mr',
  'p', 'm', 'h', 'w', 'min-h', 'min-w', 'max-h', 'max-w', 'flex', 'grid', 'items',
  'justify', 'self', 'order', 'font', 'leading', 'tracking', 'rounded', 'opacity',
  'z', 'top', 'bottom', 'left', 'right', 'inset', 'transition', 'duration', 'animate',
  'transform', 'scale', 'rotate', 'translate', 'select', 'cursor', 'list',
  'align', 'object', 'aspect', 'basis', 'grow', 'shrink', 'col', 'row', 'size',
  'backdrop', 'blur', 'brightness', 'contrast', 'drop', 'grayscale', 'invert',
  'saturate', 'sepia', 'snap', 'touch', 'scroll', 'break', 'overflow', 'whitespace',
  'uppercase', 'lowercase', 'capitalize', 'italic', 'underline', 'line-through',
  'pointer', 'resize', 'columns', 'sr',
].sort((a, b) => b.length - a.length);

const RE = new RegExp(
  `(?<![a-z-])${VARIANTS}(?:${PREFIXES.join('|')})-[a-z0-9[\\]/.%()+-]+`,
  'gi',
);

const hits = new Map();
for (const f of files) {
  const src = readFileSync(f, 'utf8');
  for (const m of src.matchAll(RE)) {
    const tok = m[0].trim();
    if (!hits.has(tok)) hits.set(tok, f);
  }
}

const missing = [];
for (const [tok, f] of hits) {
  // Tailwind escapes the whole token, variants included: .hover\:bg-white\/4:hover{
  const esc = '.' + escape(tok);
  const present =
    css.includes(esc + '{') ||
    css.includes(esc + ':') ||
    css.includes(esc + '>') ||
    css.includes(esc + ' ') ||
    css.includes(esc + ',');
  if (!present) missing.push([tok, f]);
}

console.log(`Checked ${hits.size} distinct class token(s) against ${readdirSync('dist/assets').find((x) => x.endsWith('.css'))}\n`);
console.log('MISSING (used in source, NOT generated by Tailwind):\n');
const seen = new Set();
for (const [tok, f] of missing.sort((a, b) => a[0].localeCompare(b[0]))) {
  if (seen.has(tok)) continue;
  seen.add(tok);
  console.log(`  ${tok.padEnd(30)} ${f.replace(ROOT, 'src')}`);
}
console.log(`\n${seen.size} missing.`);
